name: Salesforce Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get Salesforce key
        env:
          DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_CERTIFICATE_KEY }}
        run: |
          touch temporary_dev.key
          echo $DEPLOYMENT_KEY | base64 -d > temporary_dev.key
        shell: bash

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Authenticate with Salesforce
        env:
          SF_USERNAME: ${{ secrets.DEPLOYMENT_USER }}
          SF_CLIENTID: ${{ secrets.DEPLOYMENT_CLIENT_ID }}
        run: |
          sfdx force:auth:jwt:grant -u $SF_USERNAME -f temporary_dev.key -i $SF_CLIENTID -r https://login.salesforce.com  --setdefaultdevhubusername

      - name: Deploy to Scratch Org or Sandbox
        env:
          SF_USERNAME: ${{ secrets.DEPLOYMENT_USER }}
        run: |
          sfdx force:source:deploy -p force-app -u $SF_USERNAME --json
