name: Salesforce Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get Show key
        env:
          DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_CERTIFICATE_KEY }}
        run: |
          echo 'Inicio' 
          echo $DEPLOYMENT_KEY 
          echo 'Fin' 
        shell: bash

      - name: Get Salesforce key
        env:
          DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_CERTIFICATE_KEY }}
        run: |
          touch temporary_dev.key
          echo $DEPLOYMENT_KEY > temporary_dev.key
          # echo $DEPLOYMENT_KEY | base64 -d > temporary_dev.key
          ls -l
        shell: bash

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Authenticate with Salesforce
        env:
          SF_USERNAME: 'thesaint@principal.com'
          SF_CLIENTID: '3MVG9cHH2bfKACZbmEbZR0PfCg5iwaN43HeHlF7LBMFnmkcod0_wllbbQK8bmNQlGhPNlD5T0H7726fR3Rkxj'
        run: |
          echo 'Tail'
          tail temporary_dev.key
          sfdx force:auth:jwt:grant -u $SF_USERNAME -f server.key -i $SF_CLIENTID -r https://login.salesforce.com  --setdefaultdevhubusername
          # sfdx force:auth:jwt:grant -u $SF_USERNAME -f temporary_dev.key -i $SF_CLIENTID -r https://login.salesforce.com  --setdefaultdevhubusername

      - name: Deploy to Scratch Org or Sandbox
        env:
          SF_USERNAME: 'thesaint@principal.com'
        run: |
          sfdx force:source:deploy -p force-app -u $SF_USERNAME --json
